@startuml


System -> Dealership: get_dealership_status()
System <- Dealership: result: receiving_vehicle status
    opt receiving_vehicle == true
        System -> Dealership: add_incoming_vehicle()
    end opt

@enduml